---
- name: Execute a script.
  hosts: ic-08
  remote_user: administrator
  become: yes
  become_method: sudo
  tasks:
    - name: Execute the script 
      script: /home/administrator/programasyaourt.sh
