- hosts: imagen				 

  remote_user: administrator

  tasks:

  - name: Update packages (this is equivalent to pacman -Syu)
    pacman: update_cache=yes upgrade=yes
    become: yes
    become_method: sudo
